### ISSUE TITLE
Add CLI command for specifying relationship category

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#101]

**Comment by jessiehildebrandt** [comment]
This is already handled by the relationship attributes API (attributes are just metadata), but we will need checks to ensure that a relationship category attribute is a recognized one (and maybe autocompletion data, e.g. "set [classA,classB,myRelationship] category agg" [TAB] -> should complete "agg" to "aggregation"

**Comment by jessiehildebrandt** [comment]
We are temporarily using loose "set" and "strip" relationship attribute functions until we can implement something more prescriptive. Implemented as of #123.

**Comment by jessiehildebrandt** [comment]
2 hrs.

**Comment by dsangrey** [comment]
5 hours

**Comment by cljones97** [comment]
1 hour pair-programming
