### ISSUE TITLE
Display relationship category upon printing

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#102]

**Comment by jessiehildebrandt** [comment]
This is already handled by the relationship attributes API (attributes are just metadata), and attributes are already printed with the rest of the diagram, but we could print out unicode characters to make the relationship type more obvious (e.g. "---" - association, "-->" directed association, "--⬦" aggregation, etc.)

**Comment by jessiehildebrandt** [comment]
We will have an enhancement goal next sprint of displaying fancy lines to indicate the relationship category/type. For now, this is handled by printing the attribute specifying the type under the relationship name.
