### ISSUE TITLE
Enforce functions needing return type & parameter list

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#108]

**Comment by jessiehildebrandt** [comment]
Made irrelevant by a design decision. Functions with an empty parameter list and/or no return type will be displayed as "fn <function name>()". This is to make our model more language agnostic for languages such as JavaScript and Python.

**Comment by jessiehildebrandt** [comment]
This will be re-opened for consideration later at the customer's decision.
