### ISSUE TITLE
Enforce variables needing types

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#109]

**Comment by jessiehildebrandt** [comment]
Made irrelevant by a recent design decision. In order to be more language agnostic types are not necessary and type-less variables will simply be listed as "var <variable name>". This will allow modeling duck-typed languages such as JavaScript and Python.

**Comment by jessiehildebrandt** [comment]
This will be re-opened if the customer decides that some sort of type name should always be provided. JavaScript variables could simply be of "var" type, for example. For future consideration.
