### ISSUE TITLE
Redesign relationship storage and logic (only one relationship between a class pair)

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#116]
There should only be one relationship between a pair of classes. Relationship names are no longer necessary.

**Comment by Nick-Russell** [comment]
This redesign was not a priority for completing sprint 3. We will refocus on this for sprint 4.

**Comment by Nick-Russell** [comment]
Over 2 Discord meetings, pair-programmed for 3 hours with Jessie and the rest of the team.

+1 hour: Finished up refactor today with #131

**Comment by jessiehildebrandt** [comment]
Closed by #131.
