### ISSUE TITLE
Open file from filesystem

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#14]
Implement necessary code for opening a file from the filesystem.

**Comment by cljones97** [comment]
Save UML File hours worked:
Research: 2 hours
Coding: 1 hour

Load UML File hours worked:
Research: 1 hour
Coding: 1 hour

Bug Fixing/ Fixing code/Reviewing code:  2 hours

Setting Up Environment: Over 5 hours(Lost track of exact time, spent over many days, includes research and communication with other team members)

**Comment by jessiehildebrandt** [comment]
Several sanity checks and a yes/no prompt have been implemented for the load command.

~2 hrs.
