### ISSUE TITLE
Design/implement class attribute storage structure and internal API

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#30]
Regarding user story # 2 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603968002700)

**Comment by Nick-Russell** [comment]
1 hour testing

**Comment by jessiehildebrandt** [comment]
Some time was spent designing the API, but our internal data structures were designed with attributes in mind from the beginning

2 hrs.
