### ISSUE TITLE
Add CLI command for adding class attribute

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#31]
Regarding user story # 2 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603968002700)

**Comment by cljones97** [comment]
2 hours worked,
1 hour code review

**Comment by cljones97** [comment]
Total Allocated Time 4 hours worked,
2.5 hours code review

**Comment by Randrews545** [comment]
2 hours

**Comment by Nick-Russell** [comment]
1 hour
