### ISSUE TITLE
Add CLI command for editing class attributes

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#33]
Regarding user story # 4 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603968002700)

**Comment by cljones97** [comment]
Total hours worked 1 hour,
1 hour of researching code

**Comment by Randrews545** [comment]
1 hour

**Comment by Nick-Russell** [comment]
1 hour
