### ISSUE TITLE
Add CLI command for removing class attributes

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#34]
Regarding user story # 5 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603968002700)

**Comment by cljones97** [comment]
Total hours worked 6 hours, 
3 hours of researching,
2.5 hours of refactoring code

**Comment by Randrews545** [comment]
2 hours

**Comment by Nick-Russell** [comment]
1 hour
