### ISSUE TITLE
Design/implement relationship & relationship attribute storage structure & internal API

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#35]
Regarding user story # 6 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603968002700)

**Comment by Nick-Russell** [comment]
Added relationship API and testing
2 hours

**Comment by jessiehildebrandt** [comment]
Time was spent with Nick designing (and then redesigning shortly after) the relationships API in uml_diagram.py

3 hrs.
