### ISSUE TITLE
Add CLI command for removing a relationship

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#37]
Regarding user story # 7 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603968002700)

**Comment by cljones97** [comment]
Meeting: 2 hours of peer programming with ryan(primary)

**Comment by Randrews545** [comment]
3 hours

**Comment by Nick-Russell** [comment]
2 hours
