### ISSUE TITLE
Add CLI command for adding a relationship attribute

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#38]
Regarding user story # 8 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569604004003300)

**Comment by Nick-Russell** [comment]
Not applicable

**Comment by jessiehildebrandt** [comment]
We are temporarily using loose "set" and "strip" relationship attribute functions until we can implement something more prescriptive. Implemented as of #123.

**Comment by jessiehildebrandt** [comment]
2 hrs.

**Comment by dsangrey** [comment]
3 hours
