### ISSUE TITLE
Launch window with toolbar(s), main diagram area, and attribute side panel

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#42]
Regarding user story # 11 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603980002900)

**Comment by jessiehildebrandt** [comment]
PyQT5, PyGObject, and tkinter were all considered and experimented with at length, but we settled on using pywebview for greater cross-platform consistency

8 hrs.
