### ISSUE TITLE
Add buttons to properties panel: {add variable, delete variable, add function, delete function}

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#44]
Regarding user story # 11 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603980002900)

**Comment by jessiehildebrandt** [comment]
In progress as of #120, just missing the behavior to update the diagram model.

**Comment by Nick-Russell** [comment]
3 hours - add function & add variable buttons now display another set of input fields (visual functionality only, still need to tie into the model)

**Comment by Nick-Russell** [comment]
Buttons have been added but delete still needs functionality. This will be addressed in sprint 4.

**Comment by Nick-Russell** [comment]
I have added submit buttons for submitting class member changes.

Remaining functionality will be handled by #56 & #58.
