### ISSUE TITLE
Display class members in side panel when class clicked with selector active

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#50]
Regarding user story # 13 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603980002900)

**Comment by Randrews545** [comment]
1 hour

**Comment by Nick-Russell** [comment]
Updated to sprint 3 task

**Comment by Randrews545** [comment]
3 hours pair programming

**Comment by Nick-Russell** [comment]
Total of 5 hours (3 hours being pair programming).

Ryan and I were able to get this into an basic working state. This still needs some polish (i.e. removing class members from properties panel upon selecting a new class).

There were **a lot** of issues we encountered when trying to get the model (Python) to communicate with the view (JavaScript). This took far beyond the amount of time any of us had expected.

**Comment by Nick-Russell** [comment]
We will finish this early into sprint 4.

**Comment by Nick-Russell** [comment]
As of merge #126, the class member fields are now cleared after additional selection events.

**Comment by Nick-Russell** [comment]
This task is heavily connected with #56 & #58. Now that the basics of this issue have been covered, any additional development on this issue would relate to either #56 & #58.
