### ISSUE TITLE
Add/update class member in backend when submit button is pressed

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#56]
Regarding user story # 18 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603992003100)

**Comment by jessiehildebrandt** [comment]
In progress as of #120, just missing the behavior to update the diagram model.

**Comment by Nick-Russell** [comment]
This task needed #50 to be more well defined before much progress could be made. This will be implemented in sprint 4.

**Comment by Nick-Russell** [comment]
Updated issue to fit current design

**Comment by Nick-Russell** [comment]
Work on this for 5 hours today.

Much of the logic is now in place for this task. I will work on debugging this tomorrow.

**Comment by Nick-Russell** [comment]
Debugged and worked on this for 2 hours.
This is now implemented.
