### ISSUE TITLE
Edit class member when the text in its field is changed and entered

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#57]
Regarding user story # 19 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603992003100)

**Comment by jessiehildebrandt** [comment]
In progress as of #120, just missing the behavior to update the diagram model.

**Comment by Nick-Russell** [comment]
This task needed #50 to be more well defined before much progress could be made. This will be implemented in sprint 4.

**Comment by Nick-Russell** [comment]
Absorbed by #56
