### ISSUE TITLE
Draw relationships between associated classes in main area

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#60]
Regarding user story # 21 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603992003100)

**Comment by Randrews545** [comment]
2 hours

**Comment by jessiehildebrandt** [comment]
Initially had relationships being drawn as simple SVG line elements, ended up using [svg.connectable.js](https://github.com/loredanacirstea/svg.connectable.js) to solve this

2 hrs.
