### ISSUE TITLE
Rename relationship when its name field is edited

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#61]
Regarding user story # 22 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603992003100)

**Comment by Randrews545** [comment]
2 hours

**Comment by Nick-Russell** [comment]
We currently have no plans for implementing this.

**Comment by jessiehildebrandt** [comment]
Relationship names are being factored out and will be replaced with a "Label" property.
