### ISSUE TITLE
Add relationship attribute when type is selected from drop-down list

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#64]
Regarding user story # 24 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569604004003300)

**Comment by Nick-Russell** [comment]
Not applicable

**Comment by jessiehildebrandt** [comment]
Not a part of our UI design any longer. See prototype at #120.
