### ISSUE TITLE
Delete relationship attribute when “delete” button is clicked

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#66]
Regarding user story # 26 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569604004003300)

**Comment by Nick-Russell** [comment]
1 hour 
Added some logic for this.

**Comment by Nick-Russell** [comment]
No longer applicable for sprint 3

**Comment by jessiehildebrandt** [comment]
That might not be right-- attributes are just metadata for our UML elements, and the user should be able to modify the attributes of relationships in order to change their type, what kind of text is displayed at either endpoint, etc.

**Comment by jessiehildebrandt** [comment]
Confirmed that this is no longer a part of our UI in the current prototype at #120.
