### ISSUE TITLE
Open file system browser for selecting save/load file path

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#72]
Regarding user stories # 16 & 17 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603980002900)

**Comment by jessiehildebrandt** [comment]
pywebview supports file dialogs natively, implementation consisted of a few lines of Python

There are some cross-platform inconsistencies with the return types of the file dialog for some reason, so that needed to be accounted for

2 hrs.
