### ISSUE TITLE
Support ctrl+o to load

### ISSUE THREAD

**Issue by Nick-Russell** [mucs420f19/JJARS#73]
Regarding user story # 17 at:
[M2 UserStories](https://mu-cs420-f19-jjars.slack.com/archives/CN29CCM0D/p1569603980002900)

**Comment by jessiehildebrandt** [comment]
Currently bound to "Ctrl+L", but this will be changed to the more ubiquitous "Ctrl+O" keybinding

**Comment by jessiehildebrandt** [comment]
Solved in #114.
